module.exports = {
    env: {
        FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
        FIREBASE_API_DOMAIN: process.env.FIREBASE_API_DOMAIN,
        FIREBASE_API_DB_URL: process.env.FIREBASE_API_DB_URL,
        FIREBASE_API_PROJECT_ID: process.env.FIREBASE_API_PROJECT_ID,
        FIREBASE_API_STORAGE_BUCKET: process.env.FIREBASE_API_STORAGE_BUCKET,
        FIREBASE_API_MESSAGING_SENDER_ID: process.env.FIREBASE_API_MESSAGING_SENDER_ID,
        FIREBASE_API_APP_ID: process.env.FIREBASE_API_APP_ID,
        FIREBASE_API_MEASUREMENT_ID: process.env.FIREBASE_API_MEASUREMENT_ID,
    },
};
